server:
  port: ${ZUUL_PORT:8081}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}
  instance:
    hostname: ${DOMAIN_NAME}
    
# ZUul Routes      
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  prefix: /api
  routes:
    dminute:
      path: /dminute/**
      service-id: dminute-ms
      strip-prefix: true
    test:
      path: /sad/**
      service-id: sadr
      strip-prefix: true
    second:
      path: /demo/**
      service-id: MY-SERVICE
      strip-prefix: true
    front:
      path: /ui
      url: https://front-dminute.herokuapp.com
      strip-prefix: false
