server:
  port: ${ZUUL_PORT:8080}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
      

# ZUul Routes      
zuul:
  prefix: /api
  routes:
    dminute:
      path: /dminute/**
      service-id: dminutems
      strip-prefix: true
    test:
      path: /sad/**
      service-id: sadr
      strip-prefix: true
     demo:
      path: /demo/**
      service-id: MY-SERVICE
      strip-prefix: true
